source 'https://rubygems.org'

gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'
gem 'puma', '~> 6.0'
gem 'rack-cors', '~> 2.0'
gem 'oj', '~> 3.16'
gem 'rackup', '~> 2.1'

# TJ3 engine dependencies
gem 'term-ansicolor', '~> 1.7'
gem 'mail', '~> 2.7'

# CP-SAT optimizer
gem 'or-tools', '~> 0.17'
